In [24]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
data = pd.read_excel("train iris.xlsx", engine="openpyxl")

In [25]:
data

     sepallength  sepalwidth  petallength  petalwidth           class
0            5.7         3.8          1.7         0.3     Iris-setosa
1            5.1         3.8          1.5         0.3     Iris-setosa
2            5.4         3.4          1.7         0.2     Iris-setosa
3            5.1         3.7          1.5         0.4     Iris-setosa
4            4.6         3.6          1.0         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
107          6.4         3.1          5.5         1.8  Iris-virginica
108          6.0         3.0          4.8         1.8  Iris-virginica
109          6.9         3.1          5.4         2.1  Iris-virginica
110          6.7         3.1          5.6         2.4  Iris-virginica
111          6.9         3.1          5.1         2.3  Iris-virginica

[112 rows x 5 columns]

In [26]:
x = data.iloc[:,:-1]

In [27]:
x

     sepallength  sepalwidth  petallength  petalwidth
0            5.7         3.8          1.7         0.3
1            5.1         3.8          1.5         0.3
2            5.4         3.4          1.7         0.2
3            5.1         3.7          1.5         0.4
4            4.6         3.6          1.0         0.2
..           ...         ...          ...         ...
107          6.4         3.1          5.5         1.8
108          6.0         3.0          4.8         1.8
109          6.9         3.1          5.4         2.1
110          6.7         3.1          5.6         2.4
111          6.9         3.1          5.1         2.3

[112 rows x 4 columns]

In [28]:
y= data.iloc[:,-1]

In [29]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
107    Iris-virginica
108    Iris-virginica
109    Iris-virginica
110    Iris-virginica
111    Iris-virginica
Name: class, Length: 112, dtype: object

In [35]:
x.values

array([[5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.9, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3]])

In [36]:
y.values

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica'], dtype=object)

In [30]:
model = RandomForestClassifier()

In [31]:
model.fit(x,y)

RandomForestClassifier()

In [33]:
predictions = model.predict([[5.4, 3, 4.5,1.5]])

In [34]:
predictions

array(['Iris-versicolor'], dtype=object)

In [38]:
data = pd.read_excel("test iris.xlsx",engine="openpyxl")

In [39]:
data

    5.1  3.5  1.4  0.2      Iris-setosa
0   4.9  3.0  1.4  0.2      Iris-setosa
1   4.7  3.2  1.3  0.2      Iris-setosa
2   4.6  3.1  1.5  0.2      Iris-setosa
3   5.0  3.6  1.4  0.2      Iris-setosa
4   5.4  3.9  1.7  0.4      Iris-setosa
5   4.6  3.4  1.4  0.3      Iris-setosa
6   5.0  3.4  1.5  0.2      Iris-setosa
7   4.4  2.9  1.4  0.2      Iris-setosa
8   4.9  3.1  1.5  0.1      Iris-setosa
9   5.4  3.7  1.5  0.2      Iris-setosa
10  4.8  3.4  1.6  0.2      Iris-setosa
11  4.8  3.0  1.4  0.1      Iris-setosa
12  4.3  3.0  1.1  0.1      Iris-setosa
13  5.8  4.0  1.2  0.2      Iris-setosa
14  5.7  4.4  1.5  0.4      Iris-setosa
15  5.4  3.9  1.3  0.4      Iris-setosa
16  5.1  3.5  1.4  0.3      Iris-setosa
17  7.0  3.2  4.7  1.4  Iris-versicolor
18  6.4  3.2  4.5  1.5  Iris-versicolor
19  6.9  3.1  4.9  1.5  Iris-versicolor
20  5.5  2.3  4.0  1.3  Iris-versicolor
21  6.5  2.8  4.6  1.5  Iris-versicolor
22  5.7  2.8  4.5  1.3  Iris-versicolor
23  6.3  3.3  4.7  1.6  Iris-versicolor
24  4.9  2.4  3.3  1.0  Iris-versicolor
25  6.6  2.9  4.6  1.3  Iris-versicolor
26  5.2  2.7  3.9  1.4  Iris-versicolor
27  5.0  2.0  3.5  1.0  Iris-versicolor
28  5.9  3.0  4.2  1.5  Iris-versicolor
29  5.8  2.7  5.1  1.9   Iris-virginica
30  6.8  3.2  5.9  2.3   Iris-virginica
31  6.7  3.3  5.7  2.5   Iris-virginica
32  6.7  3.0  5.2  2.3   Iris-virginica
33  6.3  2.5  5.0  1.9   Iris-virginica
34  6.5  3.0  5.2  2.0   Iris-virginica
35  6.2  3.4  5.4  2.3   Iris-virginica
36  5.9  3.0  5.1  1.8   Iris-virginica

In [40]:
x = data.iloc[:,:-1]

In [41]:
x

    5.1  3.5  1.4  0.2
0   4.9  3.0  1.4  0.2
1   4.7  3.2  1.3  0.2
2   4.6  3.1  1.5  0.2
3   5.0  3.6  1.4  0.2
4   5.4  3.9  1.7  0.4
5   4.6  3.4  1.4  0.3
6   5.0  3.4  1.5  0.2
7   4.4  2.9  1.4  0.2
8   4.9  3.1  1.5  0.1
9   5.4  3.7  1.5  0.2
10  4.8  3.4  1.6  0.2
11  4.8  3.0  1.4  0.1
12  4.3  3.0  1.1  0.1
13  5.8  4.0  1.2  0.2
14  5.7  4.4  1.5  0.4
15  5.4  3.9  1.3  0.4
16  5.1  3.5  1.4  0.3
17  7.0  3.2  4.7  1.4
18  6.4  3.2  4.5  1.5
19  6.9  3.1  4.9  1.5
20  5.5  2.3  4.0  1.3
21  6.5  2.8  4.6  1.5
22  5.7  2.8  4.5  1.3
23  6.3  3.3  4.7  1.6
24  4.9  2.4  3.3  1.0
25  6.6  2.9  4.6  1.3
26  5.2  2.7  3.9  1.4
27  5.0  2.0  3.5  1.0
28  5.9  3.0  4.2  1.5
29  5.8  2.7  5.1  1.9
30  6.8  3.2  5.9  2.3
31  6.7  3.3  5.7  2.5
32  6.7  3.0  5.2  2.3
33  6.3  2.5  5.0  1.9
34  6.5  3.0  5.2  2.0
35  6.2  3.4  5.4  2.3
36  5.9  3.0  5.1  1.8

In [42]:
x.values

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [43]:
y= data.iloc[:,-1]

In [44]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
5         Iris-setosa
6         Iris-setosa
7         Iris-setosa
8         Iris-setosa
9         Iris-setosa
10        Iris-setosa
11        Iris-setosa
12        Iris-setosa
13        Iris-setosa
14        Iris-setosa
15        Iris-setosa
16        Iris-setosa
17    Iris-versicolor
18    Iris-versicolor
19    Iris-versicolor
20    Iris-versicolor
21    Iris-versicolor
22    Iris-versicolor
23    Iris-versicolor
24    Iris-versicolor
25    Iris-versicolor
26    Iris-versicolor
27    Iris-versicolor
28    Iris-versicolor
29     Iris-virginica
30     Iris-virginica
31     Iris-virginica
32     Iris-virginica
33     Iris-virginica
34     Iris-virginica
35     Iris-virginica
36     Iris-virginica
Name: Iris-setosa, dtype: object

In [45]:
y.values

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype=object)

In [46]:
predictions = model.predict(x.values)

In [47]:
predictions

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype=object)

measureing accuracy of our model

In [50]:
y= data.iloc[: ,-1]

In [51]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
5         Iris-setosa
6         Iris-setosa
7         Iris-setosa
8         Iris-setosa
9         Iris-setosa
10        Iris-setosa
11        Iris-setosa
12        Iris-setosa
13        Iris-setosa
14        Iris-setosa
15        Iris-setosa
16        Iris-setosa
17    Iris-versicolor
18    Iris-versicolor
19    Iris-versicolor
20    Iris-versicolor
21    Iris-versicolor
22    Iris-versicolor
23    Iris-versicolor
24    Iris-versicolor
25    Iris-versicolor
26    Iris-versicolor
27    Iris-versicolor
28    Iris-versicolor
29     Iris-virginica
30     Iris-virginica
31     Iris-virginica
32     Iris-virginica
33     Iris-virginica
34     Iris-virginica
35     Iris-virginica
36     Iris-virginica
Name: Iris-setosa, dtype: object

In [52]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
5         Iris-setosa
6         Iris-setosa
7         Iris-setosa
8         Iris-setosa
9         Iris-setosa
10        Iris-setosa
11        Iris-setosa
12        Iris-setosa
13        Iris-setosa
14        Iris-setosa
15        Iris-setosa
16        Iris-setosa
17    Iris-versicolor
18    Iris-versicolor
19    Iris-versicolor
20    Iris-versicolor
21    Iris-versicolor
22    Iris-versicolor
23    Iris-versicolor
24    Iris-versicolor
25    Iris-versicolor
26    Iris-versicolor
27    Iris-versicolor
28    Iris-versicolor
29     Iris-virginica
30     Iris-virginica
31     Iris-virginica
32     Iris-virginica
33     Iris-virginica
34     Iris-virginica
35     Iris-virginica
36     Iris-virginica
Name: Iris-setosa, dtype: object

In [53]:
y= data.iloc[:,-1]

In [54]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
5         Iris-setosa
6         Iris-setosa
7         Iris-setosa
8         Iris-setosa
9         Iris-setosa
10        Iris-setosa
11        Iris-setosa
12        Iris-setosa
13        Iris-setosa
14        Iris-setosa
15        Iris-setosa
16        Iris-setosa
17    Iris-versicolor
18    Iris-versicolor
19    Iris-versicolor
20    Iris-versicolor
21    Iris-versicolor
22    Iris-versicolor
23    Iris-versicolor
24    Iris-versicolor
25    Iris-versicolor
26    Iris-versicolor
27    Iris-versicolor
28    Iris-versicolor
29     Iris-virginica
30     Iris-virginica
31     Iris-virginica
32     Iris-virginica
33     Iris-virginica
34     Iris-virginica
35     Iris-virginica
36     Iris-virginica
Name: Iris-setosa, dtype: object

In [56]:
count =0 
for i in range (0 ,len(y)):
    if y [i] == predictions[i]:
        count = count + 1
print((count * 100) / len(y))

100.0